### ISSUE TITLE
⠀

### ISSUE THREAD

**Issue by ghost** [christopher-besch/docker_setups#1]
![image](https://user-images.githubusercontent.com/59581316/185900630-7f1832ce-f042-46b6-ab03-ff0b4438ddfe.png)

**Comment by christopher-besch** [comment]
xD
The nextcloud is already online: [nextcloud.chris-besch.com](https://nextcloud.chris-besch.com)
The Git Backup will take a few more days until I get the hardware I need.

**Comment by ghost** [comment]
ok
